### ISSUE TITLE
Embedded targets

### ISSUE THREAD

**Issue by tobyjaffey** [Kinoma/kinomajs#1]
The tech notes talk about embedded targets http://www.kinoma.com/develop/docs/technotes/kinomaJS-opensource.php

Is there a KPL variant targetting a bare-metal embedded target?

Alternatively, is there a minimal  KPL variant for just xslib without any extensions?

I'd like to understand what the minimum runtime requirements for xslib are.
Thanks.

**Comment by phoddie** [comment]
Toby --

To run XS, our JavaScript virtual machine, on bare metal you likely won't even go through KPL. XS has very relatively few external dependencies. It uses the C standard library, though it prefixes the names of all C standard library functions with c_ (e.g. c_strlen) to make it easy to redirect those to functions with different names in an RTOS. There are some additional external dependencies (a debugging socket, text case conversion, date/time) which are contained in xsPlatform.c and xsPlatform.h:

https://github.com/Kinoma/kinomajs/blob/master/xs/sources/xslib/xsPlatform.c <https://github.com/Kinoma/kinomajs/blob/master/xs/sources/xslib/xsPlatform.c>
https://github.com/Kinoma/kinomajs/blob/master/xs/sources/xslib/xsPlatform.h <https://github.com/Kinoma/kinomajs/blob/master/xs/sources/xslib/xsPlatform.h>

You can provide simple stub implementations of many of those, assuming you can tolerate the loss in functionality (e.g. no international text case conversion).

Two other relatively large pieces of code are the RegExp (xs_pcre.c) and number to string (xs_d.toa.c) libraries. RegExp could be omitted, and a simpler dtoa could be used, with the cost of some loss of JavaScript compatibility in edge cases. For our grammars which map between JavaScript and XML, we carry a copy of expat (xs_expat.c) which could also be eliminated or replaced with a less robust alternative.

We have done work in deploying XS to micro controllers running very simple RTOS. It requires some compromises, but works quite well. The compromises that are acceptable depend on the constraints of the problem you are trying to solve, of course.

-- Peter

**Comment by phoddie** [comment]
We use XS for our custom build tools. They are a good example of using XS with a small runtime - really nothing more than Standard C Library. The simplest example of that in our repository is kpr2js which we use to convert our optional KinomaXML document schema to pure JavaScript:

	https://github.com/Kinoma/kinomajs/tree/master/xs/sources/kpr2js <https://github.com/Kinoma/kinomajs/tree/master/xs/sources/kpr2js>

The .C file adds bindings to some host services (e.g. file system) that are absent from the JavaScript/ECMAScript language specification. The .XS file is the command line tool, including command line parameter parsing (lines starting at line 48).

The XS virtual machine is initialized at line 335 of the .C file:

	https://github.com/Kinoma/kinomajs/blob/master/xs/sources/kpr2js/kpr2js.c#L335 <https://github.com/Kinoma/kinomajs/blob/master/xs/sources/kpr2js/kpr2js.c#L335>

The values in xsAllocation include the symbol table modulo, the initial chunk and slot heap sizes, and the increments they grow by. These values are typically tuned way down for embedded uses. The allocations are documented in "XS in C" in section 3.1 Allocation:

	https://github.com/Kinoma/kinomajs/blob/master/xs/doc/XS_in_C.pdf <https://github.com/Kinoma/kinomajs/blob/master/xs/doc/XS_in_C.pdf>
