### ISSUE TITLE
Latest version of the source?

### ISSUE THREAD

**Issue by kartben** [Kinoma/kinomajs#2]
I wanted to debug some CoAP code but it looks like the version of the code on this repo does not include latest additions like CoAP? I am looking for e.g kprCoAP.c...

Thanks!

**Comment by phoddie** [comment]
Thanks for pointing that out. We'll get the CoAP code int the next update. I'm not certain when that will be but should be within the month.

**Comment by kartben** [comment]
Thanks for the quick reply Peter, much appreciated!
Any chance you could drop the CoAP sources on pastebin or something? I am
hoping at using the sources to figure out if there is an API to 1/
customize the listening port for the server 2/ customize the listening
socket options so as to make it part of a multicast group.

Thanks!

Le jeu. 11 juin 2015 18:39, Peter Hoddie <notifications@github.com> a
écrit :

**Comment by phoddie** [comment]
I think our legal team might kill me if we post the code anywhere other than GitHub. But, my team is happy to try to answer your questions. The best way to do that would be for you to post them on our forum (http://forum.kinoma.com). The engineering team answers questions there, usually within a day.

**Comment by basuke** [comment]
Hi, CoAP server has an option of listening port, but not for the custom socket options. We dropped the support of multicast with current release. It seems the discussion is still undergoing.

**Comment by mkellner** [comment]
CoAP is now in the source tree. kinoma/kpr/extensions/coap

**Comment by kartben** [comment]
Excellent, thank you!
