### ISSUE TITLE
balls built, what's next?

### ISSUE THREAD

**Issue by WebReflection** [Kinoma/kinomajs#3]
I'm on an x86 64bit Arch Linux and I've successfully built the
`kinomajs/bin/linux/gtk/Release/balls/balls`
binary ... however, if I launch it, nothing happens, it just hangs there.

I was hoping to be able to test some ES6 goodness provided by this engine but I'm apparently unable to do anything with this binary. Not even `--help` did anything, not sure what I am doing wrong.

Thanks for any sort of hint/clarification

**Comment by mkellner** [comment]
Kinoma’s implementation of JavaScript 6th Edition will be first available in the 3rd Quarter of this year as a free update to Kinoma Create, within the Kinoma Studio IDE, and on the KinomaJS open source repository. http://kinoma.com/media/2015/IoTline/

**Comment by WebReflection** [comment]
thanks for the info @mkellner but I am not sure how that answers my question.

I can build as suggested in the README the balls binary, how can I test/verify that in console on my linux machine? I have a Kinoma already but I'd like to test the engine on my Linux machine.

Thanks

**Comment by archite** [comment]
The framework currently only builds on 32-bit linux. Although it may be possible to cross compile from a 64-bit system, this would be quite difficult to setup.

**Comment by mkellner** [comment]
ES6 is now included in the source tree as xs6.
