### ISSUE TITLE
Call to unsafe system

### ISSUE THREAD

**Issue by ghost** [Kinoma/kinomajs#30]
https://github.com/Kinoma/kinomajs/blob/701879d37e7fe5001420e0053cd60df6b91e4553/kinoma/kpr/extensions/k4/kprK4.c#L317

**Comment by phoddie** [comment]
Thank you for reporting this issue. Unfortunately, this repository is no longer being maintained by its owner Marvell Semiconductor. Therefore, it is unlikely this issue will be investigated.
