### ISSUE TITLE
Android build fails because README file is now called "SDK Readme.txt" on Mac OS 10.10.4

### ISSUE THREAD

**Issue by abhayghatpande** [Kinoma/kinomajs#4]
The Android build.xml uses the $ANDROID_SDK/README file to check for the existence of the Android SDK. In the latest version of the SDK, the file is now called "SDK Readme.txt" on Mac OS 10.10.4 and hence the build fails.

The build proceeds after moving / copying the file to README.

Might be better to check for the existence of the SDK using some other property?

**Comment by mkellner** [comment]
Currently preparing the next release. This will be resolved soon.

**Comment by abhayghatpande** [comment]
Thanks!
