### ISSUE TITLE
Android build fails with missing resource error (@drawable/splashscreen)

### ISSUE THREAD

**Issue by abhayghatpande** [Kinoma/kinomajs#5]
Mac OS 10.10.4
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

kinomajs/tmp/android/Release/balls/ndk/project/res/layout/splashscreen.xml:27: error: Error: No resource found that matches the given name (at 'src' with value '@drawable/splashscreen').

**Comment by abhayghatpande** [comment]
This can be fixed by adding any requisite splashcreen image in the drawable directory.

The app builds and runs, but the screen is all blank (dark) after displaying the splashscreen. The app is running. 

The Mac build displays the balls bouncing around. Should I open another issue for this, or is this something that will be fixed in the upcoming update?

**Comment by mkellner** [comment]
The source has been updated. Please let us know if you continue to encounter problems.

**Comment by abhayghatpande** [comment]
It works after a clean rebuild. Now eagerly await the xs6!

**Comment by mkellner** [comment]
xs6 is included. See xs6/notes for some details.

**Comment by abhayghatpande** [comment]
Ah! I saw the directory, but didn't check the contents. Congratulations! And thank you for all your efforts.
